function delay(ms){return new Promise(r=>setTimeout(r,ms))}
async function requestText(url,attempts=2){
  const direct=isDirectSource(url);
  const targets=direct?[url,readerUrl(url)]:[readerUrl(url)];
  let last;
  for(const target of targets){
    for(let i=0;i<attempts;i++){
      try{
        const res=await fetch(target,{credentials:'omit'});
        if(!res.ok){
          if((res.status===429||res.status>=500)&&i<attempts-1){await delay(350*(i+1));continue}
          throw new Error('HTTP '+res.status);
        }
        return await res.text();
      }catch(e){
        last=e;
        if(i<attempts-1)await delay(250*(i+1));
      }
    }
  }
  throw last||new Error('Request failed');
}
async function getJSON(url){return JSON.parse(await requestText(url))}
async function getText(url){return await requestText(url)}
function imgMeta(url,timeout=6500){return new Promise(resolve=>{const im=new Image();let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(t);resolve(v)};const t=setTimeout(()=>finish(null),timeout);im.onload=()=>finish({url,width:im.naturalWidth||0,height:im.naturalHeight||0,ratio:(im.naturalHeight?(im.naturalWidth/im.naturalHeight):0)});im.onerror=()=>finish(null);im.src=url})}
function goodAspect(meta,type){if(!meta||!meta.width||!meta.height)return false;const r=meta.ratio;if(type==='album')return r>=0.55&&r<=1.15;return r>=0.45&&r<=0.9}
async function validImage(url,type){const meta=await imgMeta(url);return goodAspect(meta,type)?meta:null}
function candidateScore(name,title,type){return bestTitleScore(name,title||'',type)}
function rankImageUrls(urls,type){return [...new Set(urls||[])].sort((a,b)=>{const ap=/600x900|600x900_2x|342x482|660x930/i.test(a)?1:0;const bp=/600x900|600x900_2x|342x482|660x930/i.test(b)?1:0;return bp-ap})}
async function searchSteam(name){let best=null,bestScore=0;const seen=new Set();for(const q of queryVariants(name,'game')){try{const data=await getJSON(STEAM_SEARCH(q));const items=(data&&data.items)||[];for(const it of items){if(it.type!=='app'||seen.has(it.id))continue;seen.add(it.id);const sc=bestTitleScore(name,it.name,'game');if(sc>bestScore){bestScore=sc;best=it}}if(best&&bestScore>=1.74)return best}catch(e){}}return best&&bestScore>=.92?best:null}
function extractGridUrls(text){const found=[];const patterns=[/https?:\/\/cdn2\.steamgriddb\.com\/grid\/[^\s\"'<>]+/g,/https?:\/\/steamgriddb\.b-cdn\.net\/grid\/[^\s\"'<>]+/g];for(const re of patterns){for(const m of String(text||'').matchAll(re))found.push(m[0].replace(/&amp;/g,'&').replace(/[)'\"\\]+$/,''))}return [...new Set(found)]}
async function sgdbFallback(name){for(const q of queryVariants(name,'game')){for(const source of [SGDB_SEARCH(q),`https://r.jina.ai/http://www.steamgriddb.com/search/grids?term=${encodeURIComponent(q)}`]){try{const body=source.startsWith('https://r.jina.ai/')?await getText(source):await getText(source);const urls=rankImageUrls(extractGridUrls(body),'game');for(const u of urls){const meta=await validImage(u,'game');if(meta)return u}}catch(e){}}}return null}
async function steamCoverCandidates(id){for(const u of rankImageUrls(IMG_URLS(id),'game')){const meta=await validImage(u,'game');if(meta)return u}return null}
async function wikiExact(title,type='other'){try{const query=encodeURIComponent(title);const data=await getJSON(`https://en.wikipedia.org/api/rest_v1/page/summary/${query}`);const img=data?.originalimage?.source||data?.thumbnail?.source;if(img){const meta=await validImage(img,type);if(meta)return {url:img,title:data.title||title,score:1.8}}}catch(e){}return null}
async function wikiFallback(name,kind='other'){let best=null;for(const candidate of queryVariants(name,kind)){const exact=await wikiExact(candidate,kind);if(exact)return exact}for(const q of buildWikipediaQueries(name,kind)){try{const data=await getJSON(`https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(q)}&gsrnamespace=0&prop=pageimages|info&pithumbsize=700&format=json&origin=*`);const pages=data?.query?.pages?Object.values(data.query.pages):[];for(const p of pages){const img=p.thumbnail?.source;if(!img)continue;const sc=bestTitleScore(name,p.title||'',kind);if(sc<.62)continue;const meta=await validImage(img,kind);if(!meta)continue;if(!best||sc>best.score)best={url:img,score:sc,title:p.title}}}catch(e){}}return best&&best.score>=.62?best:null}
async function commonsFallback(name,type){try{const suffix=type==='film'?' film poster':type==='tv'?' television poster':type==='book'?' book cover':type==='album'?' album cover':type==='game'?' video game cover':' poster';const url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrsearch='+encodeURIComponent(name+suffix)+'&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url&iiurlwidth=700&format=json&origin=*';const data=await getJSON(url);const pages=data?.query?.pages?Object.values(data.query.pages):[];let best=null;for(const p of pages){const img=p.imageinfo?.[0]?.thumburl||p.imageinfo?.[0]?.url;if(!img)continue;const title=(p.title||'').replace(/^File:/i,'').replace(/\.(jpg|jpeg|png|webp)$/i,'');const sc=bestTitleScore(name,title,type);if(sc<.38)continue;const meta=await validImage(img,type);if(!meta)continue;const boost=/poster|cover|box|pack/i.test(title)?0.08:0;const score=sc+boost;if(!best||score>best.score)best={url:img,title:p.title,score}}return best&&best.score>=.46?best:null}catch(e){return null}}
async function openLibraryBook(name){for(const q of queryVariants(name,'book')){try{const url='https://openlibrary.org/search.json?title='+escUrlPart(q)+'&limit=8&fields=title,cover_i';const data=await getJSON(url);let best=null;for(const d of (data.docs||[])){if(!d.cover_i)continue;const sc=bestTitleScore(name,d.title||'','book');if(sc<.68)continue;const u=`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`;const meta=await validImage(u,'book');if(!meta)continue;if(!best||sc>best.score)best={url:u,score:sc,title:d.title}}if(best&&best.score>=.72)return best}catch(e){}}return null}
async function googleBooksFallback(name){for(const q of queryVariants(name,'book')){try{const url='https://www.googleapis.com/books/v1/volumes?q=intitle:'+escUrlPart(q)+'&maxResults=8';const data=await getJSON(url);let best=null;for(const item of (data.items||[])){const info=item.volumeInfo||{},links=info.imageLinks||{},cover=(links.extraLarge||links.large||links.medium||links.thumbnail||links.smallThumbnail);if(!cover)continue;const sc=bestTitleScore(name,info.title||'','book');if(sc<.64)continue;const u=cover.replace(/^http:/,'https:');const meta=await validImage(u,'book');if(!meta)continue;if(!best||sc>best.score)best={url:u,score:sc,title:info.title}}if(best&&best.score>=.68)return best}catch(e){}}return null}
async function tvMazeFallback(name){for(const q of queryVariants(name,'tv')){try{const data=await getJSON('https://api.tvmaze.com/search/shows?q='+escUrlPart(q));let best=null;for(const item of data||[]){const show=item.show||{},img=show.image?.original||show.image?.medium;if(!img)continue;const sc=bestTitleScore(name,show.name||'','tv');if(sc<.68)continue;const meta=await validImage(img,'tv');if(!meta)continue;if(!best||sc>best.score)best={url:img,score:sc,title:show.name}}if(best&&best.score>=.72)return best}catch(e){}}return null}
async function musicBrainzFallback(name){for(const q of queryVariants(name,'album')){try{const url='https://musicbrainz.org/ws/2/release-group/?query='+encodeURIComponent('releasegroup:'+q)+'&fmt=json&limit=8';const data=await getJSON(url);let best=null;for(const rg of (data['release-groups']||[])){const title=rg.title||'',sc=bestTitleScore(name,title,'album');if(sc<.66)continue;if(!best||sc>best.score)best={mbid:rg.id,title,score:sc}}if(best&&best.score>=.7){try{const ar=await getJSON('https://coverartarchive.org/release-group/'+best.mbid);const front=ar.images?.find(x=>x.front)||ar.images?.[0],img=front?.thumbnails?.['600']||front?.thumbnails?.['500']||front?.image;if(img&&await validImage(img,'album'))return {url:img,title:best.title,score:best.score}}catch(e){}}}catch(e){}}return null}
async function findCover(name,type='game'){
 if(type==='game'){
   const item=await searchSteam(name);if(item){const cover=await steamCoverCandidates(item.id);if(cover)return {url:cover,appid:item.id,steamName:item.name,source:'Steam'}}
   const sg=await sgdbFallback(name);if(sg)return {url:sg,appid:null,steamName:null,source:'SteamGridDB'}
   const wiki=await wikiFallback(name,'game');if(wiki)return {url:wiki.url,appid:null,steamName:wiki.title,source:'Wikipedia'}
   const commons=await commonsFallback(name,'game');if(commons)return {url:commons.url,appid:null,steamName:commons.title,source:'Wikimedia Commons'}
 } else if(type==='book'){
   const ol=await openLibraryBook(name);if(ol)return {url:ol.url,appid:null,steamName:ol.title,source:'Open Library'}
   const gb=await googleBooksFallback(name);if(gb)return {url:gb.url,appid:null,steamName:gb.title,source:'Google Books'}
   const commons=await commonsFallback(name,'book');if(commons)return {url:commons.url,appid:null,steamName:commons.title,source:'Wikimedia Commons'}
   const wiki=await wikiFallback(name,'book');if(wiki)return {url:wiki.url,appid:null,steamName:wiki.title,source:'Wikipedia'}
 } else if(type==='tv'){
   const tv=await tvMazeFallback(name);if(tv)return {url:tv.url,appid:null,steamName:tv.title,source:'TVmaze'}
   const commons=await commonsFallback(name,'tv');if(commons)return {url:commons.url,appid:null,steamName:commons.title,source:'Wikimedia Commons'}
   const wiki=await wikiFallback(name,'tv');if(wiki)return {url:wiki.url,appid:null,steamName:wiki.title,source:'Wikipedia'}
 } else if(type==='film'){
   const commons=await commonsFallback(name,'film');if(commons)return {url:commons.url,appid:null,steamName:commons.title,source:'Wikimedia Commons'}
   const wiki=await wikiFallback(name,'film');if(wiki)return {url:wiki.url,appid:null,steamName:wiki.title,source:'Wikipedia'}
 } else if(type==='album'){
   const mb=await musicBrainzFallback(name);if(mb)return {url:mb.url,appid:null,steamName:mb.title,source:'MusicBrainz / Cover Art Archive'}
   const commons=await commonsFallback(name,'album');if(commons)return {url:commons.url,appid:null,steamName:commons.title,source:'Wikimedia Commons'}
   const wiki=await wikiFallback(name,'album');if(wiki)return {url:wiki.url,appid:null,steamName:wiki.title,source:'Wikipedia'}
 } else {
   const wiki=await wikiFallback(name,'other');if(wiki)return {url:wiki.url,appid:null,steamName:wiki.title,source:'Wikipedia'}
   const commons=await commonsFallback(name,'other');if(commons)return {url:commons.url,appid:null,steamName:commons.title,source:'Wikimedia Commons'}
 }
 return null;
}

async function fetchCover(id,force=false){const g=state.games[id];if(!g||g.cover)return true;g.failed=false;try{const cached=cacheGet(g.name,g.type,force);if(cached){if(cached.found){g.cover=cached.url;g.appid=cached.appid||null;g.steamName=cached.steamName||null;g.coverSource=cached.source||'Cache';g.failed=false;save();return true}g.failed=true;save();return false}const found=await findCover(g.name,g.type);if(found){g.cover=found.url;g.appid=found.appid;g.steamName=found.steamName;g.coverSource=found.source;g.failed=false;cacheSet(g.name,g.type,{found:true,url:found.url,appid:found.appid||null,steamName:found.steamName||null,source:found.source||'Unknown'});save();return true}cacheSet(g.name,g.type,{found:false});}catch(e){cacheSet(g.name,g.type,{found:false,error:String(e?.message||e||'unknown')})}g.failed=true;save();return false}
async function runCovers(force=false){if(IN_PREVIEW){toast('Les jaquettes se chargent quand le fichier est ouvert directement dans Chrome/Edge.');return}const ids=Object.keys(state.games).filter(id=>!state.games[id].cover);if(!ids.length){updateCoverStatus();return}document.getElementById('status').textContent='Recherche des jaquettes…';document.getElementById('progress').style.width='2%';for(let i=0;i<ids.length;i+=3){await Promise.all(ids.slice(i,i+3).map(id=>fetchCover(id,force)));const have=Object.values(state.games).filter(g=>g.cover).length;document.getElementById('progress').style.width=(have/Object.keys(state.games).length*100)+'%';document.getElementById('status').textContent=`Jaquettes : ${have}/${Object.keys(state.games).length}`;render();await new Promise(r=>setTimeout(r,40))}updateCoverStatus()}
function updateCoverStatus(){const total=Object.keys(state.games).length;const have=Object.values(state.games).filter(g=>g.cover).length;document.getElementById('progress').style.width=(total?have/total*100:0)+'%';document.getElementById('status').textContent=have===total?`✓ ${have} jaquettes`:`${have}/${total} jaquettes • ${total-have} manquantes`;updateMissingButton()}
function updateMissingButton(){const btn=document.getElementById('missingBtn');if(!btn)return;const total=Object.keys(state.games).length;const missing=Object.values(state.games).filter(g=>!g.cover).length;btn.textContent=missing?`Jaquettes manquantes (${missing})`:'Jaquettes manquantes';btn.disabled=!total||!missing}
async function setCoverFromUrl(id,url){url=String(url||'').trim();if(!url)return false;if(IN_PREVIEW){toast('Les jaquettes personnalisées peuvent être ajoutées quand le fichier est ouvert directement.');return false}if(!/^https?:\/\//i.test(url)){toast('L’URL doit commencer par http:// ou https://');return false}const ok=await imgExists(url);if(!ok){toast('Cette URL ne renvoie pas une image accessible.');return false}const g=state.games[id];if(!g)return false;g.cover=url;g.coverSource='URL';g.failed=false;g._imgTry=0;cacheSet(g.name,g.type,{found:true,url,appid:null,steamName:g.name,source:'URL'});save();render();toast(`Jaquette ajoutée pour ${g.name}`);return true}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file)})}
async function setCoverFromFile(id,file){if(!file||!file.type.startsWith('image/')){toast('Choisis une image (JPG, PNG, WEBP…).');return false}if(IN_PREVIEW){toast('Les jaquettes personnalisées peuvent être ajoutées quand le fichier est ouvert directement.');return false}try{const data=await fileToDataURL(file);const g=state.games[id];if(!g)return false;g.cover=data;g.coverSource='Import local';g.failed=false;g._imgTry=0;cacheSet(g.name,g.type,{found:true,url:data,appid:null,steamName:g.name,source:'Import local'});save();render();toast(`Jaquette importée pour ${g.name}`);return true}catch(e){toast('Impossible de lire cette image.');return false}}
function openMissing(){renderMissing();document.getElementById('missingModal').classList.add('show')}
function closeMissing(){document.getElementById('missingModal').classList.remove('show')}
function renderMissing(){const list=document.getElementById('missingList');const missing=Object.entries(state.games).filter(([,g])=>!g.cover);document.getElementById('missingSummary').textContent=missing.length?`${missing.length} élément${missing.length>1?'s':''} sans jaquette. Colle une URL d’image ou dépose un fichier pour réparer chaque carte.`:'Toutes les cartes ont une jaquette.';list.innerHTML='';if(!missing.length){list.innerHTML='<div class="missing-empty">Aucune jaquette manquante 🎉</div>';return}for(const [id,g] of missing){const item=document.createElement('div');item.className='missing-item';item.innerHTML=`<div class="missing-thumb">${esc(initials(g.name))}</div><div><div class="missing-name" title="${esc(g.name)}">${esc(g.name)}</div><div class="missing-sub">${esc(g.coverSource||'Aucune source trouvée')}</div></div><div class="cover-repair"><input class="cover-url" placeholder="https://…/image.jpg" inputmode="url"><button class="primary apply-url">Ajouter</button><label class="drop-cover">📁 Déposer / choisir<input type="file" accept="image/*" hidden></label></div>`;const url=item.querySelector('.cover-url');const apply=item.querySelector('.apply-url');const drop=item.querySelector('.drop-cover');const file=item.querySelector('input[type=file]');apply.addEventListener('click',async()=>{if(await setCoverFromUrl(id,url.value))renderMissing()});url.addEventListener('keydown',async e=>{if(e.key==='Enter'){e.preventDefault();if(await setCoverFromUrl(id,url.value))renderMissing()}});drop.addEventListener('click',e=>{if(e.target!==file)file.click()});file.addEventListener('change',async e=>{if(await setCoverFromFile(id,e.target.files?.[0]))renderMissing()});['dragover','dragenter'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('over')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('over')}));drop.addEventListener('drop',async e=>{const f=e.dataTransfer.files?.[0];if(await setCoverFromFile(id,f))renderMissing()});list.appendChild(item)}}
