function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’'"“”®™]/g,'').replace(/[&]/g,' and ').replace(/[:;,+!?.,()\[\]{}\/\\–—-]+/g,' ').replace(/\s+/g,' ').trim()}
const MATCH_STOPWORDS=new Set(['the','a','an']);
const TRAILING_QUALIFIERS=/\b(?:pc|ps5|ps4|xbox(?: series [xs])?|switch(?: 2)?|steam)\b$/i;
const EDITION_QUALIFIERS=/\b(?:remastered|remaster|definitive edition|goty|game of the year|complete edition|complete collection|hd remaster|hd remastered)\b$/i;
const TYPE_QUALIFIERS={game:/\b(?:video game|game)\b$/i,film:/\b(?:film|movie)\b$/i,tv:/\b(?:tv series|television series|television|series)\b$/i,book:/\b(?:novel|book)\b$/i,album:/\b(?:album|record|soundtrack|ost)\b$/i,other:/$/};
function stripTitleNoise(s,type='other'){let x=String(s||'').trim();for(let i=0;i<3;i++){const before=x;x=x.replace(/\s*\((?:pc|ps5|ps4|xbox(?: series [xs])?|switch(?: 2)?|steam|tv series|television series|film|movie|novel|book|album|record|soundtrack|remastered|remaster|definitive edition|goty)\)\s*$/i,'');x=x.replace(/\s*\[(?:pc|ps5|ps4|xbox(?: series [xs])?|switch(?: 2)?|steam)\]\s*$/i,'');x=x.replace(/\s*[-–—:]\s*(?:pc|ps5|ps4|xbox(?: series [xs])?|switch(?: 2)?|steam)\s*$/i,'');x=x.replace(TRAILING_QUALIFIERS,'').trim();x=x.replace(EDITION_QUALIFIERS,'').trim();if(type!=='other')x=x.replace(TYPE_QUALIFIERS[type]||/$/,'').trim();if(x===before)break}return x}
function normLoose(s,type='other'){let x=stripTitleNoise(s,type);return norm(x).split(' ').filter(Boolean).filter(t=>!MATCH_STOPWORDS.has(t)).join(' ').trim()}
function tokens(s,{loose=false,type='other'}={}){const base=norm(s).split(' ').filter(Boolean);return base.filter(t=>!loose||!MATCH_STOPWORDS.has(t))}
function levenshtein(a,b){a=norm(a);b=norm(b);if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i),cur=new Array(b.length+1);for(let i=1;i<=a.length;i++){cur[0]=i;for(let j=1;j<=b.length;j++)cur[j]=a[i-1]===b[j-1]?prev[j-1]:Math.min(prev[j-1]+1,prev[j]+1,cur[j-1]);[prev,cur]=[cur,prev]}return prev[b.length]}
function tokenSimilarity(a,b,type='other'){const A=new Set(tokens(normLoose(a,type),{loose:true,type})),B=new Set(tokens(normLoose(b,type),{loose:true,type}));if(!A.size||!B.size)return {f1:0,recall:0,precision:0};let hit=0;for(const t of A)if(B.has(t))hit++;const recall=hit/A.size,precision=hit/B.size,f1=(recall+precision)?(2*recall*precision)/(recall+precision):0;return {f1,recall,precision}}
function score(a,b,type='other'){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1.8;const LA=normLoose(A,type),LB=normLoose(B,type);if(LA&&LA===LB)return 1.62;const sim=tokenSimilarity(A,B,type);const dist=levenshtein(A,B);const edit=Math.max(0,1-dist/Math.max(A.length,B.length));const containment=(B===A||B.startsWith(A+' ')||B.endsWith(' '+A)||A.startsWith(B+' ')||A.endsWith(' '+B))?1:0;let s=sim.f1*.9+edit*.12;if(containment)s+=.11;if(sim.recall===1&&sim.precision>=.5)s+=.08;return Math.min(1.6,s)}
const COMMON_ALIASES={film:{'mario bros':'The Super Mario Bros. Movie','super mario bros':'The Super Mario Bros. Movie','mario bros movie':'The Super Mario Bros. Movie','spider man into the spider verse':'Spider-Man: Into the Spider-Verse','mad max':'Mad Max: Fury Road','dune':'Dune (2021 film)'},tv:{'the last of us':'The Last of Us (TV series)','fallout':'Fallout (TV series)','the witcher':'The Witcher (TV series)','halo':'Halo (TV series)'},book:{'dune':'Dune (novel)','the witcher':'The Witcher book series','it':'It (novel)'},game:{'mario bros':'Mario Bros.','the elder scrolls oblivion remastered':'The Elder Scrolls IV: Oblivion Remastered','metal gear solid delta snake eater':'Metal Gear Solid Delta: Snake Eater'},album:{},other:{}}
function numeralVariants(s){const map={i:'1',ii:'2',iii:'3',iv:'4',v:'5',vi:'6',vii:'7',viii:'8',ix:'9',x:'10'};const words=norm(s).split(' ').map(t=>map[t]||t);return words.join(' ')}
function queryVariants(name,type='other'){const raw=String(name||'').trim(),n=norm(raw),alias=COMMON_ALIASES[type]?.[n],loose=normLoose(raw,type),trimmed=stripTitleNoise(raw,type),withoutThe=trimmed.replace(/^the\s+/i,'').trim(),roman=numeralVariants(trimmed);const variants=[raw,alias,trimmed,loose,withoutThe,roman];if(type==='film')variants.push(raw+' film',raw+' movie');if(type==='tv')variants.push(raw+' television series',raw+' tv series');if(type==='book')variants.push(raw+' novel',raw+' book');if(type==='album')variants.push(raw+' album');if(type==='game')variants.push(raw+' video game');return [...new Set(variants.map(v=>String(v||'').trim()).filter(Boolean))]}
function typeTerms(type){return type==='film'?['film','movie']:type==='tv'?['television series','tv series','television']:type==='book'?['novel','book']:type==='album'?['album','record']:type==='game'?['video game','game']:[]}
function bestTitleScore(name,candidate,type='other'){let best=0;for(const q of queryVariants(name,type))best=Math.max(best,score(q,candidate,type));return best}
function buildWikipediaQueries(name,type){const base=queryVariants(name,type),terms=typeTerms(type),out=[];for(const q of base)for(const t of ['',...terms])out.push(t?`${q} ${t}`:q);return [...new Set(out)]}
function escUrlPart(s){return encodeURIComponent(String(s||''))}
function initials(s){return String(s).split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function slugId(){return 'g'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
const TYPE_LABELS={game:'game',film:'film',tv:'tv',book:'book',album:'album',other:'other'};
const TYPE_SET=new Set(Object.keys(TYPE_LABELS));
function normType(v){const t=String(v||'').trim().toLowerCase();return TYPE_SET.has(t)?t:null}
